version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10-stretch
    working_directory: ~/react-layer-stacked
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: Install
        command: yarn install
      - run:
        name: Lint
        command: yarn run lint
      - save_cache:
        paths:
          - ~/.cache/yarn
        key: yarn-packages-{{ checksum "yarn.lock" }}