version: 2

defaults: &defaults
  working_directory: ~/react-layer-stacked
  docker:
    - image: circleci/node:10-stretch

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-layer-stacked
      - run:
          name: Auth npm
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/react-layer-stacked/.npmrc
      - run:
          name: Publish
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
        requires:
          - test
        filters:
          tags:
            only: /^v.*/
